#define RBI_CONF_RFO_HP

#define LORAWAN_RFSWITCH_PINS {PA4, PA5}
#define LORAWAN_RFSWITCH_PIN_COUNT 2
#define LORAWAN_RFSWITCH_OFF_VALUES {HIGH, LOW}
#define LORAWAN_RFSWITCH_RX_VALUES {HIGH, LOW}
#define LORAWAN_RFSWITCH_RFO_LP_VALUES {LOW, HIGH}
#define LORAWAN_RFSWITCH_RFO_HP_VALUES {LOW, HIGH}
